---
linters:
  enable-all: true
  disable:
  # WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
  # WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
  # WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
  - scopelint
  - interfacer
  - maligned
  - wsl
  - goerr113
  - lll
  - godot
  - nlreturn
  - godox
  - golint
  - exhaustivestruct  # https://github.com/mbilski/exhaustivestruct
  - funlen  # TODO
  - cyclop  # TODO
